# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 03:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text=b'Short descriptive name for this category.', max_length=200, verbose_name='\u5206\u7c7b\u6807\u9898')),
                ('subtitle', models.CharField(blank=True, default=b'', help_text=b'Some titles may be the same and cause confusion in admin UI. A subtitle makes a distinction.', max_length=200, null=True, verbose_name='\u526f\u6807\u9898')),
                ('slug', models.SlugField(help_text=b'Short descriptive unique name for use in urls.', max_length=255, unique=True, verbose_name='slug')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.Category', verbose_name='\u96b6\u5c5e\u4e8e')),
            ],
            options={
                'ordering': ('title',),
                'verbose_name': '\u7c7b\u522b',
                'verbose_name_plural': '\u7c7b\u522b\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=64, verbose_name='\u516c\u544a\u6807\u9898')),
                ('content', models.TextField(blank=True, verbose_name='\u516c\u544a\u5185\u5bb9')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='\u76f8\u518c\u6807\u9898')),
                ('slug', models.CharField(max_length=64, verbose_name='\u76f8\u518c\u6807\u793a')),
                ('cover', models.ImageField(upload_to=b'cover/', verbose_name='\u5c01\u9762\u76f8\u518c')),
                ('photolist', models.TextField(default=b'', verbose_name='\u56fe\u7247\u5217\u8868')),
                ('views', models.IntegerField(default=0, verbose_name='\u6d4f\u89c8\u6570')),
                ('likes', models.IntegerField(default=0, verbose_name='\u559c\u6b22\u6570')),
                ('count', models.IntegerField(default=0, verbose_name='\u76f8\u518c\u6570')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('ordering', models.IntegerField(default=9999, verbose_name='\u6392\u5e8f')),
                ('recommend', models.BooleanField(default=0, verbose_name='\u63a8\u8350')),
                ('status', models.BooleanField(default=False, verbose_name='\u53d1\u5e03\u72b6\u6001')),
                ('category', models.ManyToManyField(to='frontend.Category')),
            ],
            options={
                'verbose_name': '\u76f8\u518c',
                'verbose_name_plural': '\u76f8\u518c\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text=b'Short descriptive name for this tag.', max_length=200)),
                ('slug', models.SlugField(help_text=b'Short descriptive unique name for use in urls.', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': '\u6807\u7b7e',
                'verbose_name_plural': '\u6807\u7b7e\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Weblink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u7f51\u7ad9\u540d\u79f0')),
                ('icon', models.URLField(max_length=100, verbose_name='\u7f51\u7ad9\u56fe\u6807')),
                ('url', models.URLField(max_length=100, verbose_name='\u7f51\u7ad9URL')),
            ],
            options={
                'verbose_name': '\u53cb\u60c5\u94fe\u63a5',
                'verbose_name_plural': '\u53cb\u60c5\u94fe\u63a5',
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(to='frontend.Tags'),
        ),
    ]
