# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 02:44


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text=b'Short descriptive name for this category.', max_length=200, verbose_name='\u5206\u7c7b\u6807\u9898')),
                ('subtitle', models.CharField(blank=True, default=b'', help_text=b'Some titles may be the same and cause confusion in admin UI. A subtitle makes a distinction.', max_length=200, null=True, verbose_name='\u526f\u6807\u9898')),
                ('slug', models.SlugField(help_text=b'Short descriptive unique name for use in urls.', max_length=255, unique=True, verbose_name='slug')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.Category', verbose_name='\u96b6\u5c5e\u4e8e')),
                ('sites', models.ManyToManyField(blank=True, default=b'0', help_text=b'Limits category scope to selected sites.', null=True, to='sites.Site', verbose_name='\u7ad9\u70b9')),
            ],
            options={
                'ordering': ('title',),
                'verbose_name': '\u7c7b\u522b',
                'verbose_name_plural': '\u7c7b\u522b\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text=b'Short descriptive name for this tag.', max_length=200)),
                ('slug', models.SlugField(help_text=b'Short descriptive unique name for use in urls.', max_length=255, unique=True)),
                ('categories', models.ManyToManyField(blank=True, default=b'0', help_text=b'Categories to which this tag belongs.', null=True, to='category.Category')),
            ],
            options={
                'verbose_name': '\u6807\u7b7e',
                'verbose_name_plural': '\u6807\u7b7e\u7ba1\u7406',
            },
        ),
    ]
