# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 02:31


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=64, verbose_name='\\u516c\\u544a\\u6807\\u9898')),
                ('content', models.TextField(blank=True, verbose_name='\\u516c\\u544a\\u5185\\u5bb9')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='\\u53d1\\u5e03\\u65f6\\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='\\u76f8\\u518c\\u6807\\u9898')),
                ('slug', models.CharField(max_length=64, verbose_name='\\u76f8\\u518c\\u6807\\u793a')),
                ('cover', models.ImageField(upload_to=b'cover/', verbose_name='\\u5c01\\u9762\\u76f8\\u518c')),
                ('photolist', models.TextField(default=b'', verbose_name='\\u56fe\\u7247\\u5217\\u8868')),
                ('views', models.IntegerField(default=0, verbose_name='\\u6d4f\\u89c8\\u6570')),
                ('likes', models.IntegerField(default=0, verbose_name='\\u559c\\u6b22\\u6570')),
                ('count', models.IntegerField(default=0, verbose_name='\\u76f8\\u518c\\u6570')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='\\u53d1\\u5e03\\u65f6\\u95f4')),
                ('ordering', models.IntegerField(default=9999, verbose_name='\\u6392\\u5e8f')),
                ('recommend', models.BooleanField(default=0, verbose_name='\\u63a8\\u8350')),
                ('status', models.BooleanField(default=False, verbose_name='\\u53d1\\u5e03\\u72b6\\u6001')),
                ('category', models.ManyToManyField(to='category.Category')),
                ('tags', models.ManyToManyField(to='category.Tag')),
            ],
            options={
                'verbose_name': '\\u76f8\\u518c',
                'verbose_name_plural': '\\u76f8\\u518c\\u7ba1\\u7406',
            },
        ),
        migrations.CreateModel(
            name='Weblink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\\u7f51\\u7ad9\\u540d\\u79f0')),
                ('icon', models.URLField(max_length=100, verbose_name='\\u7f51\\u7ad9\\u56fe\\u6807')),
                ('url', models.URLField(max_length=100, verbose_name='\\u7f51\\u7ad9URL')),
            ],
            options={
                'verbose_name': '\\u53cb\\u60c5\\u94fe\\u63a5',
                'verbose_name_plural': '\\u53cb\\u60c5\\u94fe\\u63a5',
            },
        ),
    ]
