# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=64, verbose_name='公告标题')),
                ('content', models.TextField(blank=True, verbose_name='公告内容')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='发布时间')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='相册标题')),
                ('slug', models.CharField(max_length=64, verbose_name='相册标示')),
                ('cover', models.ImageField(upload_to='cover/', verbose_name='封面相册')),
                ('photolist', models.TextField(default='', verbose_name='图片列表')),
                ('views', models.IntegerField(default=0, verbose_name='浏览数')),
                ('likes', models.IntegerField(default=0, verbose_name='喜欢数')),
                ('count', models.IntegerField(default=0, verbose_name='相册数')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='发布时间')),
                ('ordering', models.IntegerField(default=9999, verbose_name='排序')),
                ('recommend', models.BooleanField(default=0, verbose_name='推荐')),
                ('status', models.BooleanField(default=False, verbose_name='发布状态')),
                ('category', models.ManyToManyField(to='category.Category')),
                ('tags', models.ManyToManyField(to='category.Tag')),
            ],
            options={
                'verbose_name': '相册',
                'verbose_name_plural': '相册管理',
            },
        ),
        migrations.CreateModel(
            name='Weblink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='网站名称')),
                ('icon', models.URLField(max_length=100, verbose_name='网站图标')),
                ('url', models.URLField(max_length=100, verbose_name='网站URL')),
            ],
            options={
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接',
            },
        ),
    ]
