# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 00:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'verbose_name': '公告管理', 'verbose_name_plural': '公告管理'},
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='pub_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='pub_date',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='weblink',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='weblink',
            name='url',
        ),
        migrations.AddField(
            model_name='weblink',
            name='link',
            field=models.URLField(default=datetime.datetime(2018, 2, 1, 0, 24, 8, 901973, tzinfo=utc), verbose_name='网站URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weblink',
            name='logo',
            field=models.URLField(default=django.utils.timezone.now, verbose_name='网站图标'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weblink',
            name='name',
            field=models.CharField(max_length=100, verbose_name='网站名称'),
        ),
    ]
