# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 01:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_category_parent'),
        ('frontend', '0002_auto_20180201_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='category',
        ),
        migrations.AddField(
            model_name='photo',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='category.Category', verbose_name='图片类别'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(to='category.Tag', verbose_name='图片标签'),
        ),
    ]
