# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_category_sites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text=b'Categories to which this tag belongs.', null=True, to='category.Category'),
        ),
    ]
