# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'verbose_name': '\u516c\u544a\u7ba1\u7406', 'verbose_name_plural': '\u516c\u544a\u7ba1\u7406'},
        ),
        migrations.RemoveField(
            model_name='photo',
            name='tags',
        ),
    ]
